name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: deptest
      run: sudo apt install ocl-icd-opencl-dev
    - name: configure
      run: cmake .
    - name: make
      run: make
