name: w2x-runner

on:
  pull_request:
    branches:
      - '**'
    tags:
      - '**'
  push:
    branches:
      - '**'
    tags:
      - '**'
  release:
    types: [published, created]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: vcvarsall
      run: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      shell: cmd
    - name: msbuild
      run: msbuild
      shell: cmd
