name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: opencl-dep
      run: sudo apt -y install ocl-icd-opencl-dev
    - name: opencv-dep
      run: sudo apt -y install libopencv-dev
    - name: configure
      run: cmake .
    - name: make
      run: make
