name: w2x-runner

on:
  pull_request:
    branches:
      - '**'
    tags:
      - '**'
  push:
    branches:
      - '**'
    tags:
      - '**'
  release:
    types: [published, created]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: opencv-dep-install
      run: choco install opencv
    - name: opencl-dep-install
      run: git clone https://github.com/KhronosGroup/OpenCL-Headers opencl
    - name: cmake
      run: mkdir _build && cd _build && cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_UNICODE=ON -DCMAKE_GENERATOR="Visual Studio 16 2019" -A x64 -DOPENCV_PREFIX="C:/tools/opencv/build" -DOpenCL_INCLUDE_DIR="../opencl/" -DCUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1"
      shell: cmd
    - name: msbuild
      run: |
        cd _build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        msbuild waifu2xcpp.sln /p:Configuration=Release /p:Platform=x64 -m
      shell: cmd
    - name: upload build artifact waifu2x-converter-cpp.exe
      uses: actions/upload-artifact@v1
      with:
        name: waifu2x-converter-cpp.exe
        path: "_build\Release\waifu2x-converter-cpp.exe"
    - name: upload build artifact w2xc.dll
      uses: actions/upload-artifact@v1
      with:
        name: w2xc.dll
        path: "_build\Release\w2xc.dll"
